local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0 #5.0
  publish_frequency: 2.0 #2.0
  static_map: false
  rolling_window: true
  width: 10.0 #10.0
  height: 10.0 #10.0
  resolution: 0.05
  #planner_frequency: 1.0

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: line_layer, type: "simple_layer_namespace::LineLayer"}




