scan_filter_chain:
 - name: range
   type: LaserScanRangeFilter
   params:
     use_message_range_limits: false
     lower_threshold: 0.3
     upper_threshold: 30.0
     #lower_replacement_value: -.inf
     #upper_replacement_value: .inf
