EBandPlannerROS:
 # Goal Tolerance Parameters
 xy_goal_tolerance: 0.5 #Default 0.02 , 0.5
 yaw_goal_tolerance: 6.28 #Default 1.5 . We do not care for orientation at the moment

 # Trajectory Controller Parameters 
 max_vel_lin: 0.40 #0.75
 min_vel_lin: 0.01
 max_vel_th: 0.5 #0.1
 min_vel_th: 0.0 #0.1
 min_in_place_vel_theta: 0.0
 in_place_trans_vel: 0.0
 max_translational_acceleration: 0.5 #0.5
 max_rotational_acceleration: 0.25 #1.5
 costmap_weight: 20.0 #10.0
 k_prop: 2.0 #4.0
 k_damp: 3.5 #3.5
 max_acceleration: 0.15 #0.5
 rotation_correction_threshold: 0.5 #0.5
 differential_drive: True
 rotation_threshold_multiplier: 1.0 #1.0
 disallow_hysteresis: False 
 Ctrl_Rate: 10.0 #10.0

 # Elastic Band Parameters:
 eband_min_relative_overlap: 0.7 #0.7
 eband_tiny_bubble_distance: 0.01 #0.01
 eband_tiny_bubble_expansion: 0.01 #0.01
 num_iterations_eband_optimization: 3.0 #3.0
 eband_internal_force_gain: 4.0 #1.0
 eband_external_force_gain: 2.0 #2.0
 eband_equilibrium_approx_max_recursion_depth: 4 #4.0
 eband_significant_force_lower_bound: 0.15 #0.15 

 #smoothed_eband: True
